### PR TITLE
Type script migration

### PR DESCRIPTION
**Pull request by adviyer**
### Status
**WIP**

### Description
Successfully migrated component code to TypeScript.

### Migrations
All component files have been migrated to TypeScript from JavaScript.

### Steps to Test or Reproduce

```sh
git pull
git checkout type-script-migration
npm run dev
```

Also make sure you have the updated `.env` with Supabase keys (in Slack).

### CODE REVIEW

**Comment by mdvsh** [comment]
New `.tsx` have some linting issues. Working on a quick rebase.

**Review by mdvsh — COMMENTED** [review]
Yup, that should do it! Thank you @elliotfklein 🚀

**Review by elliotfklein — COMMENTED** [review]
Great work @adviyer @svishnus @mdvsh! :clap: 

I think we could merge this now, but we should have a plan for how we finish this migration up:
- **I'd love to get the old `components/*.js` files deleted, ideally in this PR if we can**. Doing this currently creates more linter errors that I haven't been able to resolve, but otherwise the `*.tsx` files aren't being used at all (having 2 copies of the same file in `master` would get really messy I think)
- I'd also be in favor of setting up strict mode in a future PR (e.g. https://typescript-eslint.io/docs/linting/). I tried it locally, there's ~75 errors to resolve, which should be doable
- We should also move `pages`, `hooks`, and `utils` over to TS at some point

If anyone has a chance to try to remove `*.js` files and fix the linter errors, that'd be great -- otherwise, I can take another look tomorrow.

**Comment by mdvsh** [comment]
Complete with #5 . Great work here guys!

**Pull request merged**
